version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: local_onprem_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./hospita_db.sql:/docker-entrypoint-initdb.d/hospita_db.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: